### ISSUE TITLE
browserify support: Can you publish this on npm?

### ISSUE THREAD

**Issue by jsdevel** [Puigcerber/angular-capitalize-filter#2]

**Comment by Puigcerber** [comment]
Hi @jsdevel! Sure I can take care of that. I'll let you know. Cheers.

**Comment by jsdevel** [comment]
Thanks!  Really all you need to do is run `npm publish`.

**Comment by Puigcerber** [comment]
Hi @jsdevel! 

I needed also to add an `index.js` file before [publishing](https://www.npmjs.com/package/angular-capitalize-filter) it. Thanks for commenting and using the filter.

Cheers.

**Comment by jsdevel** [comment]
Thanks @Puigcerber !
