### ISSUE TITLE
Missing All Files When Bower Installing 2.2.1

### ISSUE THREAD

**Issue by alanjames1987** [Puigcerber/angular-capitalize-filter#5]
When I install version 2.2.1 of this with Bower I only get a folder containing `Gruntfile.js` and `LICENSE`.

I don't know the reason for but I don't think it's an error on my end, although it could be.

**Comment by Puigcerber** [comment]
Hi @alanjames1987! That's a really strange error. Which Bower version are you using? I've just tried with the **1.7.0** and it installs fine for me. Cheers.

**Comment by alanjames1987** [comment]
I'm using version 1.5.3 on OS X 10.9.4. I will update to the newest version and hopefully that will fix it.

Thank you.
